# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 432efe7500a7f6e3632b016aba2d76e733f5e139d0512b4c077e0a0d81a7918977d137d130fc266100cb1dcfa75d53344c9d9d1261d95dbb8440cf59ccd5d78d

test:
  secret_key_base: f63a20ade4429ba1319a1ad7f46465e7b0d8fd73b4765b9f7863f79cd4a78af1ca45ca8209471f7686ecc4041001e1fbe29c4f7f66bcf4e395afb33744b78ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
